# coding: utf-8

"""
    Check Sender API

    Описание взаимодействия с сервисом аренды кассовой техники Check Sender  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.taxes import Taxes  # noqa: E501
from swagger_client.rest import ApiException


class TestTaxes(unittest.TestCase):
    """Taxes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaxes(self):
        """Test Taxes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.taxes.Taxes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
