# coding: utf-8

"""
    Check Sender API

    Описание взаимодействия с сервисом аренды кассовой техники Check Sender  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.receipt_items import ReceiptItems  # noqa: E501
from swagger_client.rest import ApiException


class TestReceiptItems(unittest.TestCase):
    """ReceiptItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReceiptItems(self):
        """Test ReceiptItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.receipt_items.ReceiptItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
