# coding: utf-8

"""
    MyReceipt API

    Описание взаимодействия с сервисом аренды кассовой техники MyReceipt  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tax import Tax  # noqa: E501
from swagger_client.rest import ApiException


class TestTax(unittest.TestCase):
    """Tax unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTax(self):
        """Test Tax"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tax.Tax()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
