# coding: utf-8

"""
    MyReceipt API

    Описание взаимодействия с сервисом аренды кассовой техники MyReceipt  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.status_api import StatusApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.status_api.StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_device_status(self):
        """Test case for device_status

        Полная информация об устройстве  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
