# coding: utf-8

"""
    Check Sender API

    Описание взаимодействия с сервисом аренды кассовой техники Check Sender  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.device_status_response import DeviceStatusResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceStatusResponse(unittest.TestCase):
    """DeviceStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceStatusResponse(self):
        """Test DeviceStatusResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.device_status_response.DeviceStatusResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
