# coding: utf-8

# flake8: noqa

"""
    Check Sender API

    Описание взаимодействия с сервисом аренды кассовой техники Check Sender  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.receipt_api import ReceiptApi
from swagger_client.api.status_api import StatusApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.device_status_response import DeviceStatusResponse
from swagger_client.models.receipt import Receipt
from swagger_client.models.receipt_client import ReceiptClient
from swagger_client.models.receipt_items import ReceiptItems
from swagger_client.models.receipt_response import ReceiptResponse
from swagger_client.models.tax import Tax
from swagger_client.models.taxes import Taxes
from swagger_client.models.receipt_request import ReceiptRequest
